[package]
name = "decisol"
version = "0.1.0"
edition = "2024"

[dependencies]
proto_rs = { version = "0.7", default-features = false, features = [
  "fastnum",
  "stable",
], optional = true }

log = { version = "0.4", optional = true }
serde = { version = "1" }
anyhow = { version = "1" }
fastnum = { version = "0.7", features = ["serde", "numtraits"] }
num-traits = { version = "0.2", features = ["std"] }
inventory = { version = "0.3", optional = true }

[dev-dependencies]
rust_decimal = "1.39.0"


[features]
default = ["overflow_errors", "track_caller", "check_enum_kind", "conv_errors"]
build-schemas = ["dep:inventory", "proto_rs/build-schemas"]
proto = [
  "dep:proto_rs",
  "proto_rs/fastnum",
  "proto_rs/stable",
  "proto_rs/emit-proto-files",
]

track_caller = []
overflow_checks = []
overflow_errors = ["dep:log", "overflow_checks"]
overflow_panics = ["overflow_checks"]

conv_checks = []
conv_errors = ["dep:log", "conv_checks"]
conv_panics = ["conv_checks"]

check_enum_kind = []
check_enum_decimals = []
