[package]
name = "decisol"
version = "1.0.0"
edition = "2024"

[dependencies]
proto_rs = { version = "0.11", default-features = false, features = [
  "fastnum",
  "stable",
], optional = true }

fastnum = { version = "0.7.4", features = ["numtraits", "serde"] }
inventory = { version = "0.3", optional = true }
log = { version = "0.4", optional = true }
num-traits = { version = "0.2", features = ["std"] }
serde = { version = "1" }

[dev-dependencies]
rust_decimal = "1.40.0"

[features]
default = ["check_enum_kind", "conv_errors", "overflow_errors", "track_caller"]
build-schemas = ["dep:inventory", "proto", "proto_rs/build-schemas"]
proto = [
  "dep:proto_rs",
  "proto_rs/emit-proto-files",
  "proto_rs/fastnum",
  "proto_rs/stable",
]

overflow_checks = []
overflow_errors = ["dep:log", "overflow_checks"]
overflow_panics = ["overflow_checks"]
track_caller = []

conv_checks = []
conv_errors = ["conv_checks", "dep:log"]
conv_panics = ["conv_checks"]

check_enum_decimals = []
check_enum_kind = []
