//CODEGEN BELOW - DO NOT TOUCH ME
syntax = "proto3";
package decisol;

enum SolanaLamportsKind {
  TOKEN_LAMPORTS0 = 0;
  TOKEN_LAMPORTS1 = 1;
  TOKEN_LAMPORTS2 = 2;
  TOKEN_LAMPORTS3 = 3;
  TOKEN_LAMPORTS4 = 4;
  TOKEN_LAMPORTS5 = 5;
  TOKEN_LAMPORTS6 = 6;
  TOKEN_LAMPORTS7 = 7;
  TOKEN_LAMPORTS8 = 8;
  TOKEN_LAMPORTS9 = 9;
  TOKEN_LAMPORTS10 = 10;
  TOKEN_LAMPORTS11 = 11;
  TOKEN_LAMPORTS12 = 12;
  TOKEN_LAMPORTS13 = 13;
  TOKEN_LAMPORTS14 = 14;
  TOKEN_LAMPORTS15 = 15;
  TOKEN_LAMPORTS16 = 16;
  TOKEN_LAMPORTS17 = 17;
  TOKEN_LAMPORTS18 = 18;
  LAMPORTS = 19;
  WSOL = 20;
  USDC = 21;
  USD1 = 22;
  USDT = 23;
}

message QuoteLamports {
  uint64 amount = 1;
  int32 kind = 2;
}

enum TokenLamportsKind {
  TOKEN_LAMPORTS0 = 0;
  TOKEN_LAMPORTS1 = 1;
  TOKEN_LAMPORTS2 = 2;
  TOKEN_LAMPORTS3 = 3;
  TOKEN_LAMPORTS4 = 4;
  TOKEN_LAMPORTS5 = 5;
  TOKEN_LAMPORTS6 = 6;
  TOKEN_LAMPORTS7 = 7;
  TOKEN_LAMPORTS8 = 8;
  TOKEN_LAMPORTS9 = 9;
  TOKEN_LAMPORTS10 = 10;
  TOKEN_LAMPORTS11 = 11;
  TOKEN_LAMPORTS12 = 12;
  TOKEN_LAMPORTS13 = 13;
  TOKEN_LAMPORTS14 = 14;
  TOKEN_LAMPORTS15 = 15;
  TOKEN_LAMPORTS16 = 16;
  TOKEN_LAMPORTS17 = 17;
  TOKEN_LAMPORTS18 = 18;
}

message SolanaLamports {
  uint64 amount = 1;
  int32 kind = 2;
}

enum QuoteLamportsKind {
  LAMPORTS = 0;
  WSOL = 1;
  USDC = 2;
  USD1 = 3;
  USDT = 4;
}

